[package]
name = "Project_Euler_30"
version = "0.1.0"
authors = ["Anish Sundaram <anishsun@umich.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
